import {
  BellRing,
  Bot,
  ContactRound,
  Database,
  FileInput,
  Globe2,
  Headset,
  HeartHandshake,
  Inbox,
  LayoutDashboard,
  ListChecks,
  ListTodo,
  MessageCircle,
  Network,
  PanelsTopLeft,
  Plug,
  Route,
  ServerCog,
  ShieldCheck,
  Workflow,
  Zap,
} from 'lucide-react'
import type { SolutionGroup } from './solution-map.types'

export const solutionGroups: SolutionGroup[] = [
  {
    id: 'web',
    title: 'BWS Web',
    summary: 'Presença digital',
    architectureSummary:
      'Sites e páginas que apresentam o negócio com clareza e conduzem o visitante até o contato.',
    items: [
      'Sites institucionais',
      'Landing pages',
      'Portfólios',
      'Formulários',
      'Páginas de serviços',
    ],
    icon: Globe2,
    layer: 1,
    nodes: [
      { id: 'pagina', label: 'Site', icon: PanelsTopLeft, x: 50, y: 18 },
      {
        id: 'portfolio',
        label: 'Portfólio',
        icon: FileInput,
        x: 26,
        y: 70,
      },
      {
        id: 'contato',
        label: 'Contato',
        icon: MessageCircle,
        x: 74,
        y: 70,
      },
    ],
  },
  {
    id: 'sistemas',
    title: 'BWS Systems',
    summary: 'Sistemas',
    architectureSummary:
      'Clientes, orçamentos, serviços e decisões reunidos em uma ferramenta simples de acompanhar.',
    items: [
      'Sistemas comerciais',
      'Gestão de clientes',
      'Orçamentos',
      'Acompanhamento',
      'Dashboards',
      'Sistemas sob medida',
    ],
    icon: LayoutDashboard,
    layer: 2,
    nodes: [
      { id: 'crm', label: 'Clientes', icon: ContactRound, x: 50, y: 16 },
      {
        id: 'dashboard',
        label: 'Dashboard',
        icon: LayoutDashboard,
        x: 22,
        y: 35,
      },
      { id: 'portal', label: 'Serviços', icon: PanelsTopLeft, x: 78, y: 35 },
      { id: 'dados', label: 'Dados', icon: Database, x: 30, y: 78 },
      { id: 'regras', label: 'Regras', icon: ListChecks, x: 70, y: 78 },
    ],
  },
  {
    id: 'automacoes',
    title: 'BWS Automations',
    summary: 'Automação',
    architectureSummary:
      'Entradas, tarefas, avisos e integrações conectados para reduzir repetição, espera e trabalho manual.',
    items: [
      'Integrações',
      'Notificações',
      'Fluxos automáticos',
      'Automação operacional',
      'IA aplicada quando necessária',
    ],
    icon: Workflow,
    layer: 3,
    nodes: [
      { id: 'entrada', label: 'Entrada', icon: Inbox, x: 50, y: 14 },
      {
        id: 'atendimento',
        label: 'Atendimento',
        icon: Headset,
        x: 23,
        y: 29,
      },
      { id: 'automacao', label: 'Automação', icon: Bot, x: 77, y: 29 },
      { id: 'integracao', label: 'Integração', icon: Plug, x: 80, y: 62 },
      { id: 'tarefas', label: 'Tarefas', icon: ListTodo, x: 68, y: 82 },
      {
        id: 'relatorios',
        label: 'Alertas',
        icon: BellRing,
        x: 32,
        y: 82,
      },
      {
        id: 'proxima-acao',
        label: 'Próxima ação',
        icon: Route,
        x: 20,
        y: 62,
      },
      {
        id: 'acompanhamento',
        label: 'Acompanhamento',
        icon: Network,
        x: 50,
        y: 70,
      },
    ],
  },
  {
    id: 'care',
    title: 'BWS Care',
    summary: 'Suporte e evolução',
    architectureSummary:
      'Suporte, monitoramento e evolução para a tecnologia continuar útil depois da entrega.',
    items: [
      'Manutenção',
      'Suporte',
      'Monitoramento',
      'Evoluções',
      'Hospedagem',
      'Acompanhamento técnico',
    ],
    icon: HeartHandshake,
    layer: 4,
    nodes: [
      { id: 'suporte', label: 'Suporte', icon: Headset, x: 50, y: 14 },
      {
        id: 'monitoramento',
        label: 'Monitoramento',
        icon: ShieldCheck,
        x: 22,
        y: 38,
      },
      {
        id: 'hospedagem',
        label: 'Hospedagem',
        icon: ServerCog,
        x: 78,
        y: 38,
      },
      { id: 'evolucoes', label: 'Evoluções', icon: Zap, x: 28, y: 79 },
      {
        id: 'acompanhamento',
        label: 'Acompanhamento',
        icon: Route,
        x: 72,
        y: 79,
      },
    ],
  },
]
