import {
  BarChart3,
  BellRing,
  ClipboardCheck,
  ContactRound,
  FileInput,
  FileSpreadsheet,
  Globe2,
  Headset,
  HeartHandshake,
  Inbox,
  LayoutDashboard,
  MessageCircle,
  PanelsTopLeft,
  Plug,
  Route,
  ServerCog,
  ShieldCheck,
  Workflow,
  Zap,
} from 'lucide-react'
import type { SolutionGroup } from './solution-map.types'

export const solutionGroups: SolutionGroup[] = [
  {
    id: 'web',
    title: 'BWS Web',
    summary: 'Presença digital',
    architectureSummary:
      'Sites e páginas que apresentam o negócio com clareza e conduzem o visitante até o contato.',
    items: [
      'Sites institucionais',
      'Landing pages',
      'Portfólios',
      'Formulários',
      'Páginas de serviços',
    ],
    icon: Globe2,
    nodes: [
      { id: 'pagina', label: 'Site', icon: PanelsTopLeft, x: 50, y: 18 },
      {
        id: 'portfolio',
        label: 'Portfólio',
        icon: FileInput,
        x: 26,
        y: 70,
      },
      {
        id: 'contato',
        label: 'Contato',
        icon: MessageCircle,
        x: 74,
        y: 70,
      },
    ],
  },
  {
    id: 'sistemas',
    title: 'BWS Systems',
    summary: 'Sistemas',
    architectureSummary:
      'Clientes, orçamentos, serviços e decisões reunidos em uma ferramenta simples de acompanhar.',
    items: [
      'Sistemas comerciais',
      'Gestão de clientes',
      'Orçamentos',
      'Acompanhamento',
      'Dashboards',
      'Sistemas sob medida',
    ],
    icon: LayoutDashboard,
    nodes: [
      { id: 'crm', label: 'Clientes', icon: ContactRound, x: 50, y: 16 },
      {
        id: 'orcamentos',
        label: 'Orçamentos',
        icon: FileSpreadsheet,
        x: 22,
        y: 52,
      },
      {
        id: 'servicos',
        label: 'Serviços',
        icon: ClipboardCheck,
        x: 78,
        y: 52,
      },
      {
        id: 'indicadores',
        label: 'Indicadores',
        icon: BarChart3,
        x: 50,
        y: 82,
      },
    ],
  },
  {
    id: 'automacoes',
    title: 'BWS Automations',
    summary: 'Automação',
    architectureSummary:
      'Entradas, tarefas, avisos e integrações conectados para reduzir repetição, espera e trabalho manual.',
    items: [
      'Integrações',
      'Notificações',
      'Fluxos automáticos',
      'Automação operacional',
      'IA aplicada quando necessária',
    ],
    icon: Workflow,
    nodes: [
      { id: 'entrada', label: 'Entradas', icon: Inbox, x: 50, y: 16 },
      {
        id: 'fluxo',
        label: 'Fluxos',
        icon: Route,
        x: 22,
        y: 52,
      },
      {
        id: 'alertas',
        label: 'Alertas',
        icon: BellRing,
        x: 78,
        y: 52,
      },
      {
        id: 'integracoes',
        label: 'Integrações',
        icon: Plug,
        x: 50,
        y: 82,
      },
    ],
  },
  {
    id: 'care',
    title: 'BWS Care',
    summary: 'Suporte e evolução',
    architectureSummary:
      'Suporte, monitoramento e evolução para a tecnologia continuar útil depois da entrega.',
    items: [
      'Manutenção',
      'Suporte',
      'Monitoramento',
      'Evoluções',
      'Hospedagem',
      'Acompanhamento técnico',
    ],
    icon: HeartHandshake,
    nodes: [
      { id: 'suporte', label: 'Suporte', icon: Headset, x: 50, y: 14 },
      {
        id: 'monitoramento',
        label: 'Monitoramento',
        icon: ShieldCheck,
        x: 22,
        y: 52,
      },
      {
        id: 'hospedagem',
        label: 'Hospedagem',
        icon: ServerCog,
        x: 78,
        y: 52,
      },
      {
        id: 'evolucoes',
        label: 'Evoluções',
        icon: Zap,
        x: 50,
        y: 82,
      },
    ],
  },
]
